import type { Env } from '../../env'; import type { McpTool,ToolCaller } from '../module-1.1-chat/types'; import { toolFunctionName } from '../module-1.1-chat/types'; import type { McpServerHandle } from '../module-2.1-mcp-simple-server/types'; import { utilsServer } from '../module-2.1-mcp-simple-server/utils-server';
type External={id:string;name:string;url:string;token?:string;enabled:boolean}; const BUILTIN_SERVERS:Record<string,McpServerHandle>={utils:utilsServer}; const key='mcp:servers';
async function servers(env:Env){const ext:External[]=JSON.parse(await env.APP_KV?.get(key)||'[]');return [{id:'utils',name:'utils',url:'/mcp/utils',enabled:true,builtin:true},...ext]}
async function call(req:Request,env:Env){const r=await fetch(req);const x:any=await r.json();return x.result?.content?.[0]?.text||x.result||x.error}
export async function listAvailableTools(env:Env):Promise<McpTool[]>{const out:McpTool[]=[];for(const s of await servers(env))if(s.enabled)try{if(s.builtin){const r=await sHandle(s.id,env,{jsonrpc:'2.0',id:1,method:'tools/list'});for(const t of r.result.tools)out.push({serverId:s.id,...t})}else{const r:any=await fetch(s.url,{method:'POST',headers:{'content-type':'application/json',...(s.token?{authorization:`Bearer ${s.token}`}:{})},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})}).then(x=>x.json());for(const t of r.result?.tools||[])out.push({serverId:s.id,...t})}}catch(e){console.warn('MCP server unavailable',s.id,e)}return out}
async function sHandle(id:string,env:Env,b:any){const s=BUILTIN_SERVERS[id];return JSON.parse(await (await s.fetch(new Request('https://internal',{method:'POST',headers:{authorization:`Bearer ${env.MCP_ACCESS_TOKEN}`},body:JSON.stringify(b)}),env)).text())}
export async function callTool(id:string,name:string,args:unknown,env:Env){const s=(await servers(env)).find(x=>x.id===id);if(!s)throw new Error('ไม่พบ MCP server');if(s.builtin)return (await sHandle(id,env,{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})).result?.content?.[0]?.text;return call(new Request(s.url,{method:'POST',headers:{'content-type':'application/json',...(s.token?{authorization:`Bearer ${s.token}`}:{})},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})}),env)}
export async function listServers(env:Env){return servers(env)}
export async function addServer(env:Env,x:External){const a=JSON.parse(await env.APP_KV?.get(key)||'[]');a.push(x);await env.APP_KV?.put(key,JSON.stringify(a));return x}
export async function removeServer(env:Env,id:string){const a=(JSON.parse(await env.APP_KV?.get(key)||'[]') as External[]).filter(x=>x.id!==id);await env.APP_KV?.put(key,JSON.stringify(a))}
export async function toggleServer(env:Env,id:string,enabled:boolean){const a=JSON.parse(await env.APP_KV?.get(key)||'[]') as External[];const x=a.find(x=>x.id===id);if(x)x.enabled=enabled;else a.push({id,name:id,url:'',enabled});await env.APP_KV?.put(key,JSON.stringify(a))}